### PR TITLE
Allow CM file to be configured per-project

### PR DESCRIPTION
**Pull request by jez**
### Summary & Motivation

Following discussion in #9, this adds the ability to use an sml.json file to
declare which CM file ALE and Syntastic should use when getting inline build
error information.

Usage:

- Build the support files:
    - `cd ~/.vim/bundle/vim-better-sml`
    - `make`
- Add an `sml.json` file to the root of your SML project

### Commit Summary

All the real work is done in the last two commits.
The second last commit parses the JSON file and retrieves a key.
The last commit uses the retrieved key to configure Vim.

- **Rename def-use-util to vbs-util** (5ca0269)

  The scope of this program expanded outside of just dealing with
  def-use information.

- **Add json-util.sml from SML/NJ Library** (47b69a8)

  JSONUtil was added to the SML/NJ Library ~recently (v110.81), so it
  hasn't been ported to the MLton version yet.

- **Add sub-command to vbs-util for reading config** (5806d84)

  Usage:

      vbs-util config <file>.json <key>[.<key>...]

  Example:

      $ vbs-util config test/sml.json cm.make/onSave
      development.cm

- **Use new vbs-util to parse sml.json** (22984ef)

  We want to

  - tell both Syntastic and ALE where to find a CM file if one exists
  - make sure that having an sml.json file is *always* optional

### TODO

- [ ] Update README
- [ ] Update doc/vim-better-sml.txt

### CODE REVIEW

**Comment by jez** [comment]
@jonsterling Would you mind checking out this branch and letting me know if it works for you?

**Comment by jez** [comment]
Also, do you have a link to where I can read more about the format for the `sml.json` file? As in, why is it `"make/onSave"` as opposed to `"cmFile"`? (i..e, Is this something VS Code looks at, or a specific VS Code plugin?)

**Comment by jonsterling** [comment]
@jes Sweet! I'll check out this branch once I land! (traveling today)

Re: the `sml.json` thing, this is part of the [vscode-sml](https://github.com/freebroccolo/vscode-sml) mode, which is not yet well-documented; I think that `cmFile` is a better name than `make/onSave`.

**Comment by jonsterling** [comment]
@jez I'm sorry that until now I have not had time to check this out! I'm trying to build it with `make` now, but a strange thing happens on my machine:

```
mlton -show-def-use support/vbs-util.du -prefer-abs-paths true support/vbs-util.mlb
Error: /usr/lib/mlton/sml/smlnj-lib/JSON/json-lib.mlb 19.35.
  File /Users/mtf/devel/smlnj/smlnj-110.72/lib/ml-lpt-lib.cm/ml-lpt-lib.mlb does not exist.
```

It looks like at least in the version of mlton that I have installed (`20100608`), this `mlb` file contains references to what I assume are Matthew Fluet's own home directory. Weird!

**Comment by jez** [comment]
Oh hm...

I just checked; looks like I have mlton 20130715. Maybe try upgrading?
If you can't upgrade for whatever reason I can look into ways to work around it.

**Comment by jonsterling** [comment]
I guess Ubuntu packages an extremely old version of MLton, lol... Let me figure out how to get it upgraded.

**Comment by jonsterling** [comment]
@jez I had to upgrade my OS and then my MLton install, but once all was said and done, this seemed to work really well! Very nicely done.

**Comment by jonsterling** [comment]
By the way, one thing to keep in mind is I have no particular attachment to using JSON for this; if it would make the code of `vim-better-sml` simpler, we could use any configuration format.

**Comment by jez** [comment]
Eh, the code is simple enough I think (also I’d never used SML for JSON
before so that was a fun exercise).

The reality is that probably your projects are the only ones that will use
this feature in the short term, so if it works it’ll be fine to just keep
it like this.

**Pull request merged**
